/*
 * This source file was generated by the Gradle 'init' task
 */
package lab;

import java.util.List;
import java.util.Optional;

import lab.model.*;
import lab.model.exception.InsufficientParticipantsException;
import lab.model.exception.WormholeClosedException;

public class Main {
    public static void main(String[] args) {
        Person arthur = new Person("Arthur");
        Message message = arthur.say("А у меня, кажется, большие проблемы с образом жизни");

        DimensionalWeave weave = DimensionalWeave.getInstance();
        Wormhole wormhole = weave.openWormhole();
        Galaxy galaxy = new Galaxy("Far far away galaxy");
        
        try {
            wormhole.sendMessage(message, galaxy);
        } catch (WormholeClosedException e) {
            System.out.println(e.getMessage());
        }

        Creature creature1 = new Creature("Zogrim", 5);
        Creature creature2 = new Creature("Insectoid", 3);
        Creature creature3 = new Creature("Machine Mind", 3);

        try {
            Optional<War> warOptional = creature1.rollInitiative(List.of(creature2, creature3));
            if (warOptional.isPresent()) {
                System.out.println(String.format("Started war between %s, %s and %s",
                        creature1.getName(),
                        creature2.getName(),
                        creature3.getName()));
            } else {
                System.out.println("No war started: conflict resolved peacefully");
            }
        } catch (InsufficientParticipantsException e) {
            System.out.println(e.getMessage());
        }
    }
}
